steps:
  docs:
    image: julia
    pull: true
    when:
      - event: [push, manual]   # workflow should run if you execute it manually and on each push
    environment:
      FTP:
        from_secret: ftp
      FTP_USER:
        from_secret: ftp_user
      FTP_PASS:
        from_secret: ftp_pass
      CBMAIL:
        from_secret: cbmail
      CBTOKEN:
        from_secret: cbtoken
    commands:
      - export CI="1"

      - mkdir ~/NeuroAnalyzer
      - mkdir ~/NeuroAnalyzer/plugins

      - apt-get update
      - apt-get install -y xvfb ncftp git libpcre3

      - ln -s /usr/lib/x86_64-linux-gnu/libpcre.so.3 /usr/lib/x86_64-linux-gnu/libpcre.so.1

      - git clone https://codeberg.org/AdamWysokinski/NeuroAnalyzer-docs NA-docs
      - git clone --depth 1 https://codeberg.org/AdamWysokinski/NeuroAnalyzer.jl

      - cd NeuroAnalyzer.jl/docs
      - cat header.md > src/index.md
      - ./template.sh >> src/index.md
      - DISPLAY=:0 xvfb-run -a -s '-screen 0 1024x768x24' julia make_md.jl
      - cp build/index.md ../../NA-docs/Documentation.md
      - DISPLAY=:0 xvfb-run -a -s '-screen 0 1024x768x24' julia make_html.jl
      - mv build docs
      - sed -i 's/Edit on GitHub/Edit on Codeberg/g' docs/index.html
      - sed -i 's///g' docs/index.html
      - ncftpput -R -u "$FTP_USER" -p "$FTP_PASS" $FTP / docs

      - cd ../../NA-docs
      - git config --global user.email "$CBMAIL"
      - git config --global user.name "CI Builder"
      - git config --global init.defaultBranch main
      - git remote set-url origin https://$CBTOKEN@codeberg.org/AdamWysokinski/NeuroAnalyzer-docs.git
      - git add --all
      - ./push_docs.sh

  test:
    image: julia
    pull: true
    when:
      - event: manual   # workflow should run if you execute it manually
    commands:
      - export CI="1"

      - mkdir ~/NeuroAnalyzer
      - mkdir ~/NeuroAnalyzer/plugins

      - apt-get update
      - apt-get install -y xvfb

      - DISPLAY=:0 xvfb-run -a -s '-screen 0 1024x768x24' julia -e "using Pkg; Pkg.add("https://codeberg.org/AdamWysokinski/FIRLSFilterDesign.jl"); Pkg.activate(@__DIR__); Pkg.instantiate(); Pkg.test()"
