[NeuroAnalyzer_resources]
git-tree-sha1 = "c6d43d7d18005a69c8e749c3bcaa96e2cdd1c583"

    [[NeuroAnalyzer_resources.download]]
    url = "https://neuroanalyzer.org/artifacts/neuroanalyzer-resources-dev.tar.gz"
    sha256 = "4ac81814e643d5aad2f3e522d4046beabf5c924f560310268b2073e0c2e2085b"

[NeuroAnalyzer_test-files]
git-tree-sha1 = "ad21c4aff4d1435644796802e2b950741a3052f7"

    [[NeuroAnalyzer_test-files.download]]
    url = "https://neuroanalyzer.org/artifacts/neuroanalyzer-test-files-dev.tar.gz"
    sha256 = "ef81d54a1d7e64b6761c9d07cd43ce63eedcdefc264ce02f96cc344e232ce00c"
