[NeuroAnalyzer_resources]
git-tree-sha1 = "5d28931953470cdaddb1dd3f26ce9745153d072a"

    [[NeuroAnalyzer_resources.download]]
    url = "https://neuroanalyzer.org/artifacts/neuroanalyzer-resources-dev.tar.gz"
    sha256 = "4ec03a9550c9af7b8fb0742fd3e30701aa5f7d913f61d504a657fabe091e3d95"

[NeuroAnalyzer_test-files]
git-tree-sha1 = "0206d559b1fe92f5f611e4cbf19761e8799f49a4"

    [[NeuroAnalyzer_test-files.download]]
    url = "https://neuroanalyzer.org/artifacts/neuroanalyzer-test-files-dev.tar.gz"
    sha256 = "bc47ad8932ee09171c4b36e99f5789f42ad8a8048e05b532dfecf2df31b9a6c9"
