[NeuroAnalyzer_resources]
git-tree-sha1 = "e3f01b5393b845c51a054af54ef1598f0ecb0761"

    [[NeuroAnalyzer_resources.download]]
    url = "https://neuroanalyzer.org/artifacts/neuroanalyzer-resources-dev.tar.gz"
    sha256 = "d930bb1aa73e595959634c718b385ab8934668da842650aa9881996adeee4207"

[NeuroAnalyzer_test-files]
git-tree-sha1 = "ad21c4aff4d1435644796802e2b950741a3052f7"

    [[NeuroAnalyzer_test-files.download]]
    url = "https://neuroanalyzer.org/artifacts/neuroanalyzer-test-files-dev.tar.gz"
    sha256 = "ef81d54a1d7e64b6761c9d07cd43ce63eedcdefc264ce02f96cc344e232ce00c"
