export plot_efield2d

"""
    plot_efield2d(; <keyword arguments>)

Plot a 2D electric field generated by point charges.

# Arguments

- `q::Vector{Int64}`: charges values (positive or negative integers)
- `qx::Vector{Float64}`: x-axis positions of charges
- `qy::Vector{Float64}`: y-axis positions of charges
- `d::Int64`: density of field vectors; currently unused in the function, but kept for future compatibility

# Returns

- `GLMakie.Figure`: the plotted figure with electric field streamlines and charge markers

# Notes

- The electric field is computed using Coulomb's law for point charges.
- Positive charges are plotted in red, negative charges in blue, with size proportional to charge magnitude.
- The field is visualized using streamlines, with color indicating field strength.
"""
function plot_efield2d(
    q::Vector{Int64},
    qx::Vector{Float64},
    qy::Vector{Float64},
    d::Int64 = 2,
)::GLMakie.Figure
    # validate
    length(q) == length(qx) == length(qy) ||
        throw(
            ArgumentError(
                "Charge, x-position, and y-position vectors must have the same length.",
            ),
        )
    all(-5.0 .≤ qx .≤ 5.0) ||
        throw(ArgumentError("X positions must be within [-5.0, 5.0]."))
    all(-5.0 .≤ qy .≤ 5.0) ||
        throw(ArgumentError("Y positions must be within [-5.0, 5.0]."))

    # m, n = size(norm_e)
    # x = round.(collect(range(-1, 1, m)), digits=3)
    # y = round.(collect(range(-1, 1, n)), digits=3)
    # nq = length(q)

    # c = floor.(Int64, NeuroAnalyzer.normalize_n(norm_e, 15)) .+ 1
    # cl = range(colorant"lightgreen", stop=colorant"yellow", length=16)

    # prepare charge data as tuples for easier access
    qs = collect(zip(q, qx, qy))

    # electric field calculation function (Coulomb's law)
    function E(q, rx, ry, x, y)
        d = sqrt((x - rx)^2 + (y - ry)^2)^3
        return (q * (x - rx) / d, q * (y - ry) / d)
    end

    # total electric field at a point (x, y)
    function fieldE(x, y)
        Ex, Ey = 0.0, 0.0
        for (q_val, qx_val, qy_val) in qs
            ex, ey = E(q_val, qx_val, qy_val, x, y)
            Ex += ex
            Ey += ey
        end
        return Point(Ex, Ey)
    end

    # prepare plot
    GLMakie.activate!(; title = "plot_efield()")
    plot_size = (800, 800)
    fig = GLMakie.Figure(; size = plot_size)

    # create axis with customizable properties
    ax = GLMakie.Axis(
        fig[1, 1];
        aspect = DataAspect(),
        xautolimitmargin = (0, 0),
        yautolimitmargin = (0, 0),
        _AXIS_LOCK_KWARGS...,
    )
    _style_axis!(ax)

    # draw electric field streamlines
    GLMakie.streamplot!(
        ax,
        fieldE,
        -5 .. 5, -5 .. 5;
        arrow_size = 10,
        linewidth = 1,
        colorrange = (-3, 3),
        colormap = :bluesreds,
    )

    # draw charges as scatter points
    for (q_val, qx_val, qy_val) in qs
        GLMakie.scatter!(
            ax,
            Point(qx_val, qy_val);
            markersize = abs(q_val) * 20,
            color = q_val > 0 ? :red : :blue,
        )
    end

    return fig
end
