echo "# NeuroAnalyzer.jl documentation"
echo ""
echo "This documentation has been generated using [Documenter.jl](https://juliadocs.github.io/Documenter.jl/stable/)."
echo ""
echo "## NeuroAnalyzer"
echo ""
echo "\`\`\`@docs"
cat ../src/na/setup.jl | grep ^function | grep -v ^"function _" | grep -v Base. | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
cat ../src/na/plugins.jl | grep ^function | grep -v ^"function _" | grep -v Base. | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## Utils"
echo ""
echo "\`\`\`@docs"
cat ../src/utils/*.jl | grep ^function | grep -v ^"function _" | grep Base. | sed s/"function Base."/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
cat ../src/utils/*.jl | grep ^function | grep -v ^"function _" | grep -v Base. | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## Stats"
echo ""
echo "\`\`\`@docs"
cat ../src/stats/*.jl | grep ^function | grep -v ^"function _" | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## IO"
echo ""
echo "\`\`\`@docs"
cat ../src/io/*.jl | grep ^function | grep -v ^"function _" | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## Edit"
echo ""
echo "\`\`\`@docs"
cat ../src/edit/*.jl | grep ^function | grep -v ^"function _" | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## Process"
echo ""
echo "\`\`\`@docs"
cat ../src/process/*.jl | grep ^function | grep -v ^"function _" | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## Locs"
echo ""
echo "\`\`\`@docs"
cat ../src/locs/*.jl | grep ^function | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## Analyze"
echo ""
echo "\`\`\`@docs"
cat ../src/analyze/*.jl | grep ^function | grep -v ^"function _" | grep Statistics. | sed s/"function Statistics."/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
cat ../src/analyze/*.jl | grep ^function | grep -v ^"function _" | grep -v Statistics. | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## Model"
echo ""
echo "\`\`\`@docs"
cat ../src/model/*.jl | grep ^function | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## Plot"
echo ""
echo "\`\`\`@docs"
cat ../src/plots/*.jl | grep ^function | grep -v ^"function _" | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## GUI"
echo ""
echo "\`\`\`@docs"
cat ../src/gui/*.jl | grep ^function | grep -v ^"function _" | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## NeuroRecorder"
echo ""
echo "\`\`\`@docs"
cat ../src/recorder/*.jl | grep ^function | grep -v ^"function _" | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## NeuroStim"
echo ""
echo "\`\`\`@docs"
cat ../src/stim/*.jl | grep ^function | grep -v ^"function _" | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
echo ""
echo "---"
echo ""
echo "## NeuroTester"
echo ""
echo "\`\`\`@docs"
cat ../src/tester/*.jl | grep ^function | grep -v ^"function _" | sed s/"function "/"NeuroAnalyzer."/g | sed s/"(.*)"//g | sed s/" where {.*}"//g | sed s/"::.*$"//g | sort -u
echo "\`\`\`"
