echo "# NeuroAnalyzer.jl Documentation"
echo ""
echo "This documentation has been generated using [Documenter.jl](https://juliadocs.github.io/Documenter.jl/stable/)."
echo ""
echo "## NeuroAnalyzer"
echo ""
echo "\`\`\`@docs"
cat ../src/na.jl | grep ^function | sed s/"function "//g
echo "\`\`\`"
echo ""
echo "## Low-level functions"
echo ""
echo "\`\`\`@docs"
cat ../src/low_level.jl | grep ^function | sed s/"function "//g
echo "\`\`\`"
echo ""
echo "## Statistic"
echo ""
echo "\`\`\`@docs"
cat ../src/statistic.jl | grep ^function | sed s/"function "//g
echo "\`\`\`"
echo ""
echo "## EEG I/O"
echo ""
echo "\`\`\`@docs"
cat ../src/eeg_io.jl | grep ^function | sed s/"function "//g
echo "\`\`\`"
echo ""
echo "## EEG edit"
echo ""
echo "\`\`\`@docs"
cat ../src/eeg_edit.jl | grep ^function | sed s/"function "//g
echo "\`\`\`"
echo ""
echo "## EEG process"
echo ""
echo "\`\`\`@docs"
cat ../src/eeg_process.jl | grep ^function | sed s/"function "//g
echo "\`\`\`"
echo ""
echo "## EEG analyze"
echo ""
echo "\`\`\`@docs"
cat ../src/eeg_analyze.jl | grep ^function | sed s/"function "//g
echo "\`\`\`"
echo ""
echo "## EEG plots"
echo ""
echo "\`\`\`@docs"
cat ../src/eeg_plots.jl | grep ^function | sed s/"function "//g
echo "\`\`\`"
echo ""
echo "## Neurostimulation"
echo ""
echo "\`\`\`@docs"
cat ../src/nstim.jl | grep ^function | sed s/"function "//g
echo "\`\`\`"
echo ""
echo "## NIRS"
echo ""
echo "\`\`\`@docs"
cat ../src/nirs.jl | grep ^function | sed s/"function "//g
echo "\`\`\`"
echo ""
echo "## MRI"
echo ""
echo "\`\`\`@docs"
cat ../src/mri.jl | grep ^function | sed s/"function "//g
echo "\`\`\`"